# 1. What is the difference between iloc and reshape. Explain with one example

In [5]:
import numpy as np
import pandas as pd
ip = np.arange(1,7,1)
op = np.array([10,12,14,16,18,20])
print(ip.ndim,op.ndim)
print(ip,op)

1 1
[1 2 3 4 5 6] [10 12 14 16 18 20]


In [2]:
d = {'x':ip,'y':op}
df = pd.DataFrame(d)
df


x   y
0  1  10
1  2  12
2  3  14
3  4  16
4  5  18
5  6  20

In [4]:
x = df.iloc[:,[0]].values
print(x.ndim)
print(x)

2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [6]:
print(ip.ndim)
print(ip.shape)

1
(6,)


In [13]:
x = ip.reshape(-1,1)
print(x.ndim)
print(x.shape)
x.ndim
print(x)

2
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


# 2. Difference between ide and *compiler*

# 3. How numbers are immutable?


Simple put, a mutable object can be changed after it is created, and an immutable object can't. Objects of built-in types like (int, float, bool, str, tuple, unicode) are immutable. Objects of built-in types like (list, set, dict) are mutable. Custom classes are generally mutable.

# 4.Where is Boolean Data type used?

# 5. How is list different from variable in terms of allocation of memory

---





In [0]:
#Taking a variable and assigning that variables value to another variable
a =10 
b =a
print(id(a))
print(id(b))

10914784
10914784


In [0]:
#When the value of 2nd variable is assigned to a value check whether the first varible value changes or not
b = 0
print(a) # It changes and so does the id value
print(id(a))
print(id(b))

10
10914784
10914464


In [0]:
list1 = [1,2,3,4]
list2 = list1
print(id(list1))
print(id(list2))

139772602184776
139772602184776


In [0]:
list2[1] = 0
print(list1)
print(id(list1))
print(id(list2))
# The value of id doesnt change

[1, 0, 3, 4]
139772602184776
139772602184776


With list2 = list1, you don't actually have two lists. The assignment just copies the reference to the list, not the actual list, so both list1 and list2 refer to the same list after the assignment.

Reference : https://stackoverflow.com/questions/2612802/how-to-clone-or-copy-a-list

# 6. How to use for loop for other conditions.
Ex: How to write a code for displaying numbers from 10 to 0 using for loop

In [0]:
for i in range(10,0,-1):
  print(i)

10
9
8
7
6
5
4
3
2
1


# 7. How to change upper to lowercase?

In [0]:
a = 'Ameer'
a.upper()

'AMEER'

In [0]:
li.

AttributeError: ignored